image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      flutter upgrade
      flutter update-packages --force-upgrade
      flutter run -d web-server --no-resident
ports:
  - port: 8080
    onOpen: notify
vscode:
  extensions:
    - Dart-Code.dart-code@3.13.2:VctB/eBxSv/owCFRO3X0fA==
    - Dart-Code.flutter@3.13.2:Eu9AIooF0l9SZOqPOxXFHQ==